In [121]:
import numpy as np
import pandas as pd

In [122]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')
date = date.drop(columns=['product_id','city_id','orders'])

In [123]:
date.head()

         date
0  2019-12-10
1  2018-08-15
2  2018-10-23
3  2019-08-17
4  2019-01-06

In [124]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [125]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
dtypes: object(1)
memory usage: 7.9+ KB

In [126]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

### Working with Dates

In [127]:
date['date'] = pd.to_datetime(date['date'])

In [128]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 7.9 KB

## 1.Extract year

In [129]:
date['date_year'] = date['date'].dt.year
date.head()

        date  date_year
0 2019-12-10       2019
1 2018-08-15       2018
2 2018-10-23       2018
3 2019-08-17       2019
4 2019-01-06       2019

## 2.Extract month

In [130]:
date['date_month_no'] = date['date'].dt.month
date.head()

        date  date_year  date_month_no
0 2019-12-10       2019             12
1 2018-08-15       2018              8
2 2018-10-23       2018             10
3 2019-08-17       2019              8
4 2019-01-06       2019              1

In [131]:
date['date_month_name'] = date['date'].dt.month_name()
date.head()

        date  date_year  date_month_no date_month_name
0 2019-12-10       2019             12        December
1 2018-08-15       2018              8          August
2 2018-10-23       2018             10         October
3 2019-08-17       2019              8          August
4 2019-01-06       2019              1         January

## 3.Extract days

In [132]:
date['date_day'] = date['date'].dt.day
date.head()

        date  date_year  date_month_no date_month_name  date_day
0 2019-12-10       2019             12        December        10
1 2018-08-15       2018              8          August        15
2 2018-10-23       2018             10         October        23
3 2019-08-17       2019              8          August        17
4 2019-01-06       2019              1         January         6

In [133]:
date['date_dow'] = date['date'].dt.dayofweek
date.head()

        date  date_year  date_month_no date_month_name  date_day  date_dow
0 2019-12-10       2019             12        December        10         1
1 2018-08-15       2018              8          August        15         2
2 2018-10-23       2018             10         October        23         1
3 2019-08-17       2019              8          August        17         5
4 2019-01-06       2019              1         January         6         6

In [134]:
date['date_dow_name'] = date['date'].dt.day_name()
date.head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name
0,2019-12-10,2019,12,December,10,1,Tuesday
1,2018-08-15,2018,8,August,15,2,Wednesday
2,2018-10-23,2018,10,October,23,1,Tuesday
3,2019-08-17,2019,8,August,17,5,Saturday
4,2019-01-06,2019,1,January,6,6,Sunday

In [135]:
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday','Saturday']),1,0)
date.head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

### 4.Extract week of the year

In [136]:
date['date_week'] = date['date'].dt.isocalendar().week
date.head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,2019,1,January,6,6,Sunday,1,1

### 5.Extract Quarter

In [137]:
date['quarter'] = date['date'].dt.quarter
date.head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

### 6.Extract Semester

In [138]:
date['semester'] = np.where(date['quarter'].isin([1,2]),1,2)
date.head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1,1

### Extract Time elapsed between dates

In [139]:
import datetime

today = datetime.datetime.today()
today

datetime.datetime(2026, 1, 15, 16, 25, 26, 312593)

In [140]:
today - date['date']

0     2228 days 16:25:26.312593
1     2710 days 16:25:26.312593
2     2641 days 16:25:26.312593
3     2343 days 16:25:26.312593
4     2566 days 16:25:26.312593
                 ...
995   2656 days 16:25:26.312593
996   2597 days 16:25:26.312593
997   2445 days 16:25:26.312593
998   2510 days 16:25:26.312593
999   2284 days 16:25:26.312593
Name: date, Length: 1000, dtype: timedelta64[ns]

In [141]:
(today - date['date']).dt.days

0      2228
1      2710
2      2641
3      2343
4      2566
       ...
995    2656
996    2597
997    2445
998    2510
999    2284
Name: date, Length: 1000, dtype: int64

In [142]:
# month passed
np.round((today - date['date'])/np.timedelta64(1,'m'),0)

0      3209305.0
1      3903385.0
2      3804025.0
3      3374905.0
4      3696025.0
         ...
995    3825625.0
996    3740665.0
997    3521785.0
998    3615385.0
999    3289945.0
Name: date, Length: 1000, dtype: float64

In [143]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [144]:
time['date'] = pd.to_datetime(time['date'])
time = time.drop(columns=['msg'])
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 7.9 KB

In [145]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second
time.head()

                 date  hour  min  sec
0 2013-12-15 00:50:00     0   50    0
1 2014-04-29 23:40:00    23   40    0
2 2012-12-30 00:21:00     0   21    0
3 2014-11-28 00:31:00     0   31    0
4 2013-10-26 23:11:00    23   11    0

In [146]:
time['time'] = time['date'].dt.time
time.head()

                 date  hour  min  sec      time
0 2013-12-15 00:50:00     0   50    0  00:50:00
1 2014-04-29 23:40:00    23   40    0  23:40:00
2 2012-12-30 00:21:00     0   21    0  00:21:00
3 2014-11-28 00:31:00     0   31    0  00:31:00
4 2013-10-26 23:11:00    23   11    0  23:11:00

In [147]:
today-time['date']

0     4414 days 15:35:26.312593
1     4278 days 16:45:26.312593
2     4764 days 16:04:26.312593
3     4066 days 15:54:26.312593
4     4463 days 17:14:26.312593
                 ...
995   5053 days 15:35:26.312593
996   4374 days 17:11:26.312593
997   4839 days 16:48:26.312593
998   4955 days 16:51:26.312593
999   4227 days 17:00:26.312593
Name: date, Length: 1000, dtype: timedelta64[ns]

In [148]:
# in seconds

(today-time['date'])/np.timedelta64(1,'s')

0      3.814257e+08
1      3.696795e+08
2      4.116675e+08
3      3.513597e+08
4      3.856653e+08
           ...
995    4.366353e+08
996    3.779755e+08
997    4.181501e+08
998    4.281727e+08
999    3.652740e+08
Name: date, Length: 1000, dtype: float64

In [151]:
# minutes
(today-time['date'])/np.timedelta64(1,'m')

0      6.357095e+06
1      6.161325e+06
2      6.861124e+06
3      5.855994e+06
4      6.427754e+06
           ...
995    7.277255e+06
996    6.299591e+06
997    6.969168e+06
998    7.136211e+06
999    6.087900e+06
Name: date, Length: 1000, dtype: float64

In [152]:
# hours
(today-time['date'])/np.timedelta64(1,'h')

0      105951.590642
1      102688.757309
2      114352.073976
3       97599.907309
4      107129.240642
           ...
995    121287.590642
996    104993.190642
997    116152.807309
998    118936.857309
999    101465.007309
Name: date, Length: 1000, dtype: float64