In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings

In [26]:
from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

from sklearn.preprocessing import KBinsDiscretizer
from sklearn.compose import ColumnTransformer

In [27]:
df = pd.read_csv('train.csv')[['Survived','Age','SibSp','Parch','Survived','Fare']]
df.dropna(inplace=True)
df.head()

   Survived   Age  SibSp  Parch  Survived     Fare
0         0  22.0      1      0         0   7.2500
1         1  38.0      1      0         1  71.2833
2         1  26.0      0      0         1   7.9250
3         1  35.0      1      0         1  53.1000
4         0  35.0      0      0         0   8.0500

In [28]:
df['family'] = df['SibSp'] + df['Parch']
df.head()

   Survived   Age  SibSp  Parch  Survived     Fare  family
0         0  22.0      1      0         0   7.2500       1
1         1  38.0      1      0         1  71.2833       1
2         1  26.0      0      0         1   7.9250       0
3         1  35.0      1      0         1  53.1000       1
4         0  35.0      0      0         0   8.0500       0

In [29]:
df.drop(columns=['SibSp','Parch'],inplace=True)
df.head()

   Survived   Age  Survived     Fare  family
0         0  22.0         0   7.2500       1
1         1  38.0         1  71.2833       1
2         1  26.0         1   7.9250       0
3         1  35.0         1  53.1000       1
4         0  35.0         0   8.0500       0

In [30]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [31]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)
X_train.head()

      Age     Fare  family
328  31.0  20.5250       2
73   26.0  14.4542       1
253  30.0  16.1000       1
719  33.0   7.7750       0
666  25.0  13.0000       0

In [32]:
clf = DecisionTreeClassifier()
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
accuracy_score(y_test,y_pred)

0.6503496503496503

In [33]:
np.mean(cross_val_score(DecisionTreeClassifier(),X,y,cv=10,scoring='accuracy'))

np.float64(0.6401212832550861)

In [34]:
from sklearn.preprocessing import Binarizer

In [35]:
trf = ColumnTransformer([('bin',Binarizer(copy=False),['family'])],
                       remainder='passthrough')
trf

ColumnTransformer(remainder='passthrough',
                  transformers=[('bin', Binarizer(copy=False), ['family'])])

In [36]:
X_train_trf = trf.fit_transform(X_train)
X_test_trf = trf.fit_transform(X_test)

In [37]:
pd.DataFrame(X_train_trf,columns=['Age','Fare','family'])

     Age  Fare    family
0    1.0  31.0   20.5250
1    1.0  26.0   14.4542
2    1.0  30.0   16.1000
3    0.0  33.0    7.7750
4    0.0  25.0   13.0000
..   ...   ...       ...
566  1.0  46.0   61.1750
567  0.0  25.0   13.0000
568  0.0  41.0  134.5000
569  1.0  33.0   20.5250
570  0.0  33.0    7.8958

[571 rows x 3 columns]

In [38]:
clf = DecisionTreeClassifier()
clf.fit(X_train_trf,y_train)
y_pred2 = clf.predict(X_test_trf)
accuracy_score(y_test,y_pred2)

0.6223776223776224

In [39]:
X_trf = trf.fit_transform(X)
np.mean(cross_val_score(DecisionTreeClassifier(),X_trf,y,cv=10,scoring='accuracy'))

np.float64(0.6317683881064163)